name: dev_dbx
description: ''
version: 0.0.1
author: jan.petrik@datasentics.com
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: devdbx
  parentArtefactID: janpetrikdatasenticscomteam
  buildSystem: wheel
  author: null
  createdAt: '2025-04-08 08:05:41'
pipelines:
  pipelines/dev_dbx:
    name: dev_dbx
    description: ''
    author: jan.petrik@datasentics.com
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2025-04-08 08:05:41'
    datasets:
      inputs:
      - datasets/input_account
      - datasets/input_transaction
      - datasets/prophecy_poc_input_account_type
      outputs:
      - datasets/out_agg_transaction
    subgraphs: []
    dependencies: {}
datasets:
  datasets/prophecy_poc_input_account_type:
    name: prophecy_poc_input_account_type
    description: ''
    author: jan.petrik@datasentics.com
    createdAt: '2025-04-08 08:53:12'
    mode: batch
    physicalDatasets:
      dev_dbx_python:
        fabricId: 24041
        datasetType: Database
        description: ''
        author: jan.petrik@datasentics.com
        createdAt: '2025-04-08 08:53:12'
  datasets/input_account:
    name: input_account
    description: ''
    author: jan.petrik@datasentics.com
    createdAt: '2025-04-08 08:53:56'
    mode: batch
    physicalDatasets:
      dev_dbx_python:
        fabricId: 24041
        datasetType: Database
        description: ''
        author: jan.petrik@datasentics.com
        createdAt: '2025-04-08 08:53:56'
  datasets/input_transaction:
    name: input_transaction
    description: ''
    author: jan.petrik@datasentics.com
    createdAt: '2025-04-08 08:54:05'
    mode: batch
    physicalDatasets:
      dev_dbx_python:
        fabricId: 24041
        datasetType: Database
        description: ''
        author: jan.petrik@datasentics.com
        createdAt: '2025-04-08 08:54:05'
  datasets/out_agg_transaction:
    name: out_agg_transaction
    description: ''
    author: jan.petrik@datasentics.com
    createdAt: '2025-04-08 10:00:32'
    mode: batch
    physicalDatasets:
      dev_dbx_python:
        fabricId: 24041
        datasetType: Database
        description: ''
        author: jan.petrik@datasentics.com
        createdAt: '2025-04-08 10:00:32'
templates: {}
jobs:
  jobs/poc_prophecy:
    name: poc_prophecy
    description: ''
    fabricUID: 24041
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: small
    scheduleCron: 0 30 11 * * ? *
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines:
    - pipelines/dev_dbx
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: true
    createdAt: '2025-04-08 10:04:37'
    author: jan.petrik@datasentics.com
    models: []
    sqlProjects: []
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2025-04-08 08:05:41'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2025-04-08T08:05:41.243759Z'
  name: plibMaven
  version: 8.8.2
  id: '1130531150'
  createdAt: '2025-04-08T08:05:41.243759Z'
  type: plibMaven
- modifiedAt: '2025-04-08T08:05:41.243759Z'
  name: plibPypi
  version: 1.9.36
  id: '1281196516'
  createdAt: '2025-04-08T08:05:41.243759Z'
  type: plibPypi
projectDependencies:
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.8
    isDefault: true
    author: null
    createdAt: '2025-04-08 08:01:32'
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.42
    isDefault: true
    author: null
    createdAt: '2025-04-08 08:01:32'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
